TRUNCATE TABLE Vote RESTART IDENTITY;
TRUNCATE TABLE Users RESTART IDENTITY;
TRUNCATE TABLE Menu_Meal RESTART IDENTITY;
TRUNCATE TABLE Menu RESTART IDENTITY;
TRUNCATE TABLE Meal RESTART IDENTITY;
TRUNCATE TABLE Restaurant RESTART IDENTITY;

-- DELETE FROM Vote;
-- DELETE FROM Users;
-- DELETE FROM Menu;
-- DELETE FROM Meal;
-- DELETE FROM Restaurant;
