TRUNCATE TABLE Vote RESTART IDENTITY;
TRUNCATE TABLE Users RESTART IDENTITY;
TRUNCATE TABLE Menu_Dish RESTART IDENTITY;
TRUNCATE TABLE Menu RESTART IDENTITY;
TRUNCATE TABLE Dish RESTART IDENTITY;
TRUNCATE TABLE Restaurant RESTART IDENTITY;
